### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jeffcharles** [MarioAriasC/funKTionale#10]
I'd like to use this library in an application of mine. Would you be willing to add an open source license like Apache or MIT to the project? I could create a pull request to do it if you'd like.

**Comment by MarioAriasC** [comment]
The project is Apache 2.0, each single file has a license header. I'll add a note on the `README.md` file

**Comment by jeffcharles** [comment]
Ah, I typically look for a LICENSE file in the root of the project
