### ISSUE TITLE
DEXOPT error on Android 4.2 and older

### ISSUE THREAD

**Issue by daemontus** [MarioAriasC/funKTionale#3]
Hi,

when using this library on Android 4.2 and older, I get an INSTALL_FAILED_DEXOPT. It might have something to do with this problem: http://stackoverflow.com/questions/21434837/installing-kotlin-android-project-fails-with-install-failed-dexopt
After recompiling funKTionale with latest Kotlin (Beta 2), everything works fine. Could you please upload a recompiled version to the official maven repo? Many thanks.

**Comment by MarioAriasC** [comment]
Fixed https://github.com/MarioAriasC/funKTionale/releases/tag/0.6_1.0.0-beta-3594

**Comment by daemontus** [comment]
Awesome, thank you very much.
