### ISSUE TITLE
Would you share the script to generate functions with multiple generic params?

### ISSUE THREAD

**Issue by vjames19** [MarioAriasC/funKTionale#31]
In your talk you said you have a script to generate functions like this:

```kotlin
infix inline fun <P1, R> P1.pipe(t: (P1) -> R): R = t(this)

infix inline fun <P1, P2, R> P1.pipe2(crossinline t: (P1, P2) -> R): (P2) -> R = { p2 -> t(this, p2) }

infix inline fun <P1, P2, P3, R> P1.pipe3(crossinline t: (P1, P2, P3) -> R): (P2, P3) -> R = { p2, p3 -> t(this, p2, p3) }
```

Would you mind sharing it? 

I want to automate the generation of functions like that.

**Comment by MarioAriasC** [comment]
https://github.com/MarioAriasC/funKTionale/blob/master/funktionale-experimental/src/main/kotlin/org/funktionale/generators/generate.kt Enjoy

**Comment by vjames19** [comment]
Thanks!
