### ISSUE TITLE
Hi, gradle compile maybe not work at 1.2 version 

### ISSUE THREAD

**Issue by fly7632785** [MarioAriasC/funKTionale#40]
```
repositories {
    mavenCentral()
    jcenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'org.funktionale:funktionale:1.2'
}
```

**Comment by MarioAriasC** [comment]
`dependencies {
    compile 'org.funktionale:funktionale:1.2'
}`

Isn't a valid dependency, do you mean `funktionale-all`?

**Comment by fly7632785** [comment]
yes, maybe my use is wrong. I used to 0.8, just change to 1.2
“ compile 'org.funktionale:funktionale-all:1.2'”   is ok
Thanks, by the way. This is a good lib.
